### ISSUE TITLE
Unknown enum values in map

### ISSUE THREAD

**Issue by graphman65** [google/protobuf.dart#538]
Hello,

Right now, if we have some protobuf definition like this:

```protobuf
enum Value {
    VALUE_INVALID = 0;
    VALUE_A = 1;
    VALUE_B = 2;
}

message Message {
    map<string, Value> values = 1;
}
```

The protobuf library will parse it correctly.
But now let's suppose we add another value to the enum. 

```protobuf
enum Value {
    VALUE_INVALID = 0;
    VALUE_A = 1;
    VALUE_B = 2;
    VALUE_C = 3;
}

message Message {
    map<string, Value> values = 1;
}
```
Clients generated with the first version (without `VALUE_C`) crashes when parsing a message containing this new value.
And we end up with "DATA_LOSS" when using the grpc lib.

Reading the spec and to match what is happening for enum values outside of maps, I think we should use the default value when we find some unknown enum value in a map. Or we could do the same as what the library is currently doing for lists => skip the value.  

This might be related to #508 and #536 but is also happening without using null safety.

**Comment by osa1** [comment]
Thanks for reporting this.

> Reading the spec and to match what is happening for enum values outside of maps, I think we should use the default value when we find some unknown enum value in a map. Or we could do the same as what the library is currently doing for lists => skip the value.

This is not right. [The spec](https://developers.google.com/protocol-buffers/docs/proto3#enum) says this:

> During deserialization, unrecognized enum values will be preserved in the message, though how this is represented when the message is deserialized is language-dependent. In languages that support open enum types with values outside the range of specified symbols, such as C++ and Go, the unknown enum value is simply stored as its underlying integer representation. In languages with closed enum types such as Java, a case in the enum is used to represent an unrecognized value, and the underlying integer can be accessed with special accessors. In either case, if the message is serialized the unrecognized value will still be serialized with the message.

So when we see an unrecognized enum constant (e.g. `VALUE_C` in your example) we need to store it as "unrecognized" with the integer for it so that when we serialize the message we will be able to serialize the unrecognized enum value. We can't use the default value or just skip the entry in a map as that changes the message.

---

It seems like we currently don't handle unrecognized enum values at all. Using your proto example, without `VALUE_C` in the enum, this example:

```dart
Message msg = Message.create();
msg.mergeFromProto3Json({'values': {'test': 'VALUE_C'}});
```

fails with:

```
Unhandled exception:
FormatException: Protobuf JSON decoding failed at: root["values"]["test"]. Unknown enum value
VALUE_C
#0      _mergeFromProto3Json.recursionHelper.convertProto3JsonValue (package:protobuf/src/protobuf/proto3_json.dart:215:13)
#1      _mergeFromProto3Json.recursionHelper.<anonymous closure>.<anonymous closure> (package:protobuf/src/protobuf/proto3_json.dart:370:21)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#3      _mergeFromProto3Json.recursionHelper.<anonymous closure> (package:protobuf/src/protobuf/proto3_json.dart:364:21)
#4      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#5      _mergeFromProto3Json.recursionHelper (package:protobuf/src/protobuf/proto3_json.dart:339:14)
#6      _mergeFromProto3Json (package:protobuf/src/protobuf/proto3_json.dart:416:3)
#7      GeneratedMessage.mergeFromProto3Json (package:protobuf/src/protobuf/generated_message.dart:270:7)
#8      main (file:///Users/omersa/dart/protobuf_test/bin/main.dart:7:7)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

Binary decoding also fails with an exception, though the exception is different:

```dart
final Uint8List buffer = Uint8List.fromList([10, 8, 10, 4, 116, 101, 115, 116, 16, 3]);
Message msg = Message.fromBuffer(buffer);
```

Output:

```
Unhandled exception:
Null check operator used on a null value
#0      PbMap._mergeEntry (package:protobuf/src/protobuf/pb_map.dart:110:72)
#1      _mergeFromCodedBufferReader (package:protobuf/src/protobuf/coded_buffer.dart:189:14)
#2      GeneratedMessage.mergeFromBuffer (package:protobuf/src/protobuf/generated_message.dart:196:5)
#3      new Message.fromBuffer (file:///Users/omersa/dart/protobuf_test/test.pb.dart:32:125)
#4      main (file:///Users/omersa/dart/protobuf_test/bin/main.dart:17:25)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

I will have to think more for how to represent unrecognized enums best.

**Comment by osa1** [comment]
Thanks for reporting this.

> Reading the spec and to match what is happening for enum values outside of maps, I think we should use the default value when we find some unknown enum value in a map. Or we could do the same as what the library is currently doing for lists => skip the value.

This is not right. [The spec](https://developers.google.com/protocol-buffers/docs/proto3#enum) says this:

> During deserialization, unrecognized enum values will be preserved in the message, though how this is represented when the message is deserialized is language-dependent. In languages that support open enum types with values outside the range of specified symbols, such as C++ and Go, the unknown enum value is simply stored as its underlying integer representation. In languages with closed enum types such as Java, a case in the enum is used to represent an unrecognized value, and the underlying integer can be accessed with special accessors. In either case, if the message is serialized the unrecognized value will still be serialized with the message.

So when we see an unrecognized enum constant (e.g. `VALUE_C` in your example) we need to store it as "unrecognized" with the integer for it so that when we serialize the message we will be able to serialize the unrecognized enum value. We can't use the default value or just skip the entry in a map as that changes the message.

---

It seems like we currently don't handle unrecognized enum values at all. Using your proto example, without `VALUE_C` in the enum, this example:

```dart
Message msg = Message.create();
msg.mergeFromProto3Json({'values': {'test': 'VALUE_C'}});
```

fails with:

```
Unhandled exception:
FormatException: Protobuf JSON decoding failed at: root["values"]["test"]. Unknown enum value
VALUE_C
#0      _mergeFromProto3Json.recursionHelper.convertProto3JsonValue (package:protobuf/src/protobuf/proto3_json.dart:215:13)
#1      _mergeFromProto3Json.recursionHelper.<anonymous closure>.<anonymous closure> (package:protobuf/src/protobuf/proto3_json.dart:370:21)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#3      _mergeFromProto3Json.recursionHelper.<anonymous closure> (package:protobuf/src/protobuf/proto3_json.dart:364:21)
#4      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#5      _mergeFromProto3Json.recursionHelper (package:protobuf/src/protobuf/proto3_json.dart:339:14)
#6      _mergeFromProto3Json (package:protobuf/src/protobuf/proto3_json.dart:416:3)
#7      GeneratedMessage.mergeFromProto3Json (package:protobuf/src/protobuf/generated_message.dart:270:7)
#8      main (file:///Users/omersa/dart/protobuf_test/bin/main.dart:7:7)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

Binary decoding also fails with an exception, though the exception is different:

```dart
final Uint8List buffer = Uint8List.fromList([10, 8, 10, 4, 116, 101, 115, 116, 16, 3]);
Message msg = Message.fromBuffer(buffer);
```

Output:

```
Unhandled exception:
Null check operator used on a null value
#0      PbMap._mergeEntry (package:protobuf/src/protobuf/pb_map.dart:110:72)
#1      _mergeFromCodedBufferReader (package:protobuf/src/protobuf/coded_buffer.dart:189:14)
#2      GeneratedMessage.mergeFromBuffer (package:protobuf/src/protobuf/generated_message.dart:196:5)
#3      new Message.fromBuffer (file:///Users/omersa/dart/protobuf_test/test.pb.dart:32:125)
#4      main (file:///Users/omersa/dart/protobuf_test/bin/main.dart:17:25)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

I will have to think more for how to represent unrecognized enums best.
