### ISSUE TITLE
Deserialization Fails for URLs / URL encoded strings

### ISSUE THREAD

**Issue by RCHowell** [google/protobuf.dart#551]
I have some message which has a field where I want to send a url.
```protobuf
message Request {
  string url = 1;
}
```

Here are the ways I've tried to set it
```dart
Request(url: url) // HTML URL encoded, preferred
Request(url: Uri.decodeFull(url)) // this changes the meaning in the given context
```

And here is how I've tried to post the this body to my server, 
```dart
// Basic
client.post(
  path: '...',
  data: String.fromCharCodes(req.writeToBuffer()),
);

// Improved
client.post(
  path: '...',
  data: utf8.decode(req.writeToBuffer(), allowMalformed: false),
);
```

The basic post fails on the server-side (Kotlin) with

```
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
        at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:107)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readStringRequireUtf8(CodedInputStream.java:821)
```

The improved post fails client-side (Flutter) because I suppose it's an invalid utf-8 string. The exception is simply
```
FormatException: Unexpected extension byte (at offset 1)
```

The URLs are actually coming from Firebase Storage. I'm unsure where to open this issue, because I'm not confident this is a protobuf issue. Any advice helps.

I opened this issue to protobuf.dart because I need a way to post the raw HTML URL encoded strings in my protobuf object. 

For now, I will just use the `bytes` type because it looks like the protobuf objects must be serializable to UTF-8, and in doing so, I actually change the URLs meaning in the context of Firebase Storage.

**Comment by osa1** [comment]
Would it be possible for you to share the Dart string you use for the `url` field in your message? Ideally the code unit list (`string.codeUnits`).

If we know the string then we can test that we can serialize it in a proto message and deserialize it back to the original string. Without the string or some kind of repro I don't think we can debug any issues with your setup or the protobuf library.

Please feel free to re-open with a repro, or with the `url` string in your example.
