### ISSUE TITLE
"Attempted to change read-only message" even though message is not frozen/read-only

### ISSUE THREAD

**Issue by osa1** [google/protobuf.dart#628]
Proto:

```proto
syntax = "proto3";

message M1 {
  M2 nested = 1;
}

message M2 {
  M3 nested = 1;
}

message M3 {
  int32 i = 1;
}
```

Dart:

```dart
import '../test.pb.dart';

void main() {
  M1 m1 = M1.create();
  m1.nested.nested.i = 123;
  print(m1);
}
```

Output:

```
Unhandled exception:
Unsupported operation: Attempted to change a read-only message (M3)
#0      defaultFrozenMessageModificationHandler (package:protobuf/src/protobuf/field_set.dart:16:3)
#1      _FieldSet._ensureWritable (package:protobuf/src/protobuf/field_set.dart:207:54)
#2      _FieldSet._$set (package:protobuf/src/protobuf/field_set.dart:545:5)
#3      GeneratedMessage.$_setSignedInt32 (package:protobuf/src/protobuf/generated_message.dart:492:15)
#4      M3.i= (file:///Users/omersa/dart/protobuf_test/test.pb.dart:150:24)
#5      main (file:///Users/omersa/dart/protobuf_test/bin/main.dart:7:20)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

**Comment by osa1** [comment]
This is a duplicate of #309.

When we create an empty `M1` the message fields should be `null`. When we return a read-only empty message, code like `m1.nested.nested` in the repro above works even though it shouldn't. And because the messages we generate on-the-fly with getters `nested` are read-only the assignment `m1.nested.nested.i = ...`.

@sigurdm points out that it doesn't make sense to initialize the uninitialized message fields with mutable default messages because it changes presence checks just by accessing the fields. So if we create a mutable default message with `m1.nested` in the repro above, `m1.hasNested()` returns `false` before the access and returns `true` after it, even if we don't update the nested message.

So the right thing to do here (as also discussed in #309) is to return `null` for uninitialized message fields. Returning read-only empty message is confusing at best, and probably also not compliant to the spec (see https://github.com/google/protobuf.dart/issues/309#issuecomment-1085024825 and the next comment).
