### ISSUE TITLE
`GeneratedMessage.toBuilder` fails to un-freeze nested messages

### ISSUE THREAD

**Issue by osa1** [google/protobuf.dart#629]
Proto:

```proto
syntax = "proto3";

message M1 {
  M2 nested = 1;
}

message M2 {
  M3 nested = 1;
}

message M3 {
  int32 i = 1;
}
```

Dart:

```dart
import '../test.pb.dart';

void main() {
  M1 m1 = M1.fromJson('''{"1": {"1": {"1": 123}}}''');
  m1.freeze();
  M1 m1Mutable = m1.toBuilder() as M1;
  m1Mutable.nested.nested.i = 456;
}
```

Output:

```
Unhandled exception:
Unsupported operation: Attempted to change a read-only message (M3)
#0      defaultFrozenMessageModificationHandler (package:protobuf/src/protobuf/field_set.dart:16:3)
#1      _FieldSet._ensureWritable (package:protobuf/src/protobuf/field_set.dart:207:54)
#2      _FieldSet._$set (package:protobuf/src/protobuf/field_set.dart:545:5)
#3      GeneratedMessage.$_setSignedInt32 (package:protobuf/src/protobuf/generated_message.dart:492:15)
#4      M3.i= (file:///Users/omersa/dart/protobuf_test/test.pb.dart:150:24)
#5      main (file:///Users/omersa/dart/protobuf_test/bin/main.dart:7:27)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

The problem is `toBuilder` is implemented as shallow copy so it cannot un-freeze nested messages: https://github.com/google/protobuf.dart/blob/767ce8152ab2b56d1f9bb3554f0e5f9552cc15d2/protobuf/lib/src/protobuf/generated_message.dart#L90-L94

**Comment by osa1** [comment]
This is working as intended, as documented a few lines above the quoted code in my original message: https://github.com/google/protobuf.dart/blob/57312421192cdc8b8dcb94ec4d42c36432917a28/protobuf/lib/src/protobuf/generated_message.dart#L79-L87

This design was initially a bit strange to me, but it actually makes a lot of sense from a performance standpoint. If I want to modify top-level of a deeply nested message I should be able to copy just one layer and modify it, instead of cloning the whole tree. This API makes it possible.
